### ISSUE TITLE
CM network policy

### ISSUE THREAD

**Issue by rbaumgar** [open-cluster-management-io/policy-collection#17]
can you please add a network policy like

```
    - complianceType: "musthave"
      objectDefinition:
        kind: NetworkPolicy
        apiVersion: networking.k8s.io/v1
        metadata:
          namespace: default
          name: deny-from-other-namespaces
        spec:
          podSelector:
            matchLabels:
          ingress:
          - from:
            - podSelector: {} # accept ingress from all pods within this namespace only
```
