### ISSUE TITLE
Create a Policy for Managed-ClusterSetBinding

### ISSUE THREAD

**Issue by ch-stark** [open-cluster-management-io/policy-collection#275]
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedClusterSetBinding
metadata:
  namespace: policies
  name: default
spec:
  clusterSet: default

**Comment by gparvin** [comment]
This probably won't work unless you already have a namespace bound to a cluster set and a policy being distributed to that namespace.  Be aware that you need the ManagedClusterSetBinding for placement to place this policy.  

Since this is a binding needed only on the hub for user policies, what do you think about us doing this with `ManifestWork`?  I haven't thought this through a lot -- but it looks like subscriptions use ManifestWork for their setup -- and this seems to be a similar case.

**Comment by ch-stark** [comment]
Hi Gus, thanks for the feedback, if we have an example how ManifestWork will help here, I'm happy to investigate

**Comment by gparvin** [comment]
Right -- since this is all on the hub, I would think the prereq for doing policy work is just to create this:

```
apiVersion: v1
kind: Namespace
metadata:
  name: policies
spec: {}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedClusterSetBinding
metadata:
  namespace: policies
  name: default
spec:
  clusterSet: default
```

Since it's a prereq, we need something other than policy to create this unless there's an existing namespace and existing `ManagedClusterSetBinding` we could rely on which could then be used with policy.
