### ISSUE TITLE
kubeadmin removal policy has wrong namespaceSelector

### ISSUE THREAD

**Issue by duritong** [open-cluster-management-io/policy-collection#299]
In https://github.com/stolostron/policy-collection/blob/ad66e6b90a83f6f98d044596b42bc0c436d4a879/community/SC-System-and-Communications-Protection/policy-remove-kubeadmin.yaml

We have a:

```
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
```

And at the same time want that the kubeadmin Secret in `kube-system` is removed. But kube-system is excluded through the selector.
