### ISSUE TITLE
Provide a Policy for DRPlacementControl

### ISSUE THREAD

**Issue by ch-stark** [open-cluster-management-io/policy-collection#342]
During manual failover when working with ODF the following object has been created.
This is to investigate if a Policy should be created

```
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: pacman-placement-1-drpc
  namespace: pacman
  finalizers:
    - drpc.ramendr.openshift.io/finalizer
  labels:
    app: pacman
    cluster.open-cluster-management.io/backup: resource
spec:
  action: Failover
  drPolicyRef:
    name: ocp4perf1-ocp4perf2-2m
  failoverCluster: ocp4perf2
  placementRef:
    kind: PlacementRule
    name: pacman-placement-1
    namespace: pacman
  preferredCluster: ocp4perf1
  pvcSelector: {}
```
