### ISSUE TITLE
Kyverno installation policy not working

### ISSUE THREAD

**Issue by gforster** [open-cluster-management-io/policy-collection#386]
I am getting the following error across multiple clusters that indicate Kyverno isn't actually getting installed from the `policy-install-kyverno-prod-ns` template:

violation - customresourcedefinitions not found: [policyreports.wgpolicyk8s.io] missing; violation - couldn't find mapping resource with kind Application, please check if you have CRD deployed; notification - subscriptions [kyverno-subscription-1] in namespace kyverno found as specified, therefore this Object template is compliant; violation - couldn't find mapping resource with kind PlacementRule, please check if you have CRD deployed; violation - couldn't find mapping resource with kind Channel, please check if you have CRD deployed

I can confirm there is nothing created in the `kyverno` or `kyverno-channel` namespaces

**Comment by dhaiducek** [comment]
Hi @gforster! Thanks for opening an issue!

Looking at those errors, it looks like the Application Lifecycle functionality isn't present on the cluster since the CRDs for Channel and PlacementRule from `apps.open-cluster-management.io` are missing. Do all the managed clusters have Application Lifecycle enabled?

**Comment by ydguala** [comment]
I also see the problem when using the `community/CM-Configuration-Management/policy-install-kyverno.yaml`

```yaml
oc -n local-cluster get  ConfigurationPolicy policy-install-kyverno-prod-ns -o yaml
.
.
.
status:
  compliancyDetails:
  - Compliant: NonCompliant
    Validity: {}
    conditions:
    - lastTransitionTime: "2023-04-21T09:03:13Z"
      message: 'customresourcedefinitions [policyreports.wgpolicyk8s.io] is missing,
        and cannot be created, reason: `CustomResourceDefinition.apiextensions.k8s.io
        "policyreports.wgpolicyk8s.io" is invalid: [metadata.name: Invalid value:
        "policyreports.wgpolicyk8s.io": must be spec.names.plural+"."+spec.group,
        spec.group: Required value, spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion(nil):
        must have exactly one version marked as storage version, spec.names.plural:
        Required value, spec.names.singular: Required value, spec.names.kind: Required
        value, spec.names.listKind: Required value, status.storedVersions: Invalid
        value: []string(nil): must have at least one stored version]`'
      reason: K8s creation error
      status: "True"
      type: violation
```

**Comment by ydguala** [comment]
In my case, my placement rule for kyverno was having the default cluster selector defined in the policy and which my clusters did not have. Modifying this solve 

```
.
.
.
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: apps.open-cluster-management.io/v1
                kind: PlacementRule
                metadata:
                  name: kyverno-placement-1
                  namespace: kyverno
                  labels:
                    app: kyverno
                spec:
                  clusterSelector:                      
                    matchLabels:
                      environment: dev                     # THIS WAS THE PROBLEM 
```
