### ISSUE TITLE
OPA Policy to Protect Namespaces from Accidental Deletion

### ISSUE THREAD

**Issue by abdennour** [open-cluster-management-io/policy-collection#421]
Hi, 

  I was trying to use the native syntax of OPA/Gatekeeper, but it seems like there Gatekeeper of Redhat Marketplace is not the same as community one: 

Anyway, this is the policy, which does not take effect unfortunetely: 

```yaml
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: preventdeletingallnamespaces
spec:
  crd:
    spec:
      names:
        kind: PreventDeletingAllNamespaces
      validation:
        # Schema for the `PreventDeletingAllNamespaces` CR
        # This CR will be used to enforce the constraint
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
  # Parameters for the OPA policy
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package preventdeletingallnamespaces

        # import data.kubernetes.namespaces
        # import data.lib.openshift.namespaces
        # Deny deletion if the namespace doesn't have the required annotation
        violation[msg] {
            input.request.operation == "DELETE"
            input.request.kind.kind == "Namespace"
            # not namespace_has_allow_delete_annotation(input.request.namespace)
            msg := sprintf("Deletion of namespace '%v' is not allowed as it is not annotated with allow-delete=true", [input.request.namespace])
        }

        # Check if the namespace has the required annotation
        namespace_has_allow_delete_annotation(namespace) {
            namespaces[namespace].metadata.annotations["allow-delete"] == "true"
        }

---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PreventDeletingAllNamespaces
metadata:
  name: preventdeletingallnamespaces
spec: {}
```
testing it :
```sh
oc create ns test-hello
oc delete ns test-hello
# It was not denied !?
```

Could you please provide a working policy with the same purpose?
