### ISSUE TITLE
Can't apply label with empty values not applied on nodes

### ISSUE THREAD

**Issue by schabrolles** [open-cluster-management-io/policy-collection#425]
HI all,

I'm trying to create a policy to install automatically ODF on an openshift cluster.
For that, I need to label some nodes with `cluster.ocs.openshift.io/openshift-storage: ""`

My policy says: 
> notification - nodes [worker1.pink.edu.ihost.com] found as specified, therefore this Object template is compliant

But the label is not there :/ 

Here is the ComplicancePolicy used:

```
 apiVersion: policy.open-cluster-management.io/v1
  kind: ConfigurationPolicy
  metadata:
    name: odf-label-nodes
  spec:
    object-templates:
      - complianceType: musthave
        objectDefinition:
          apiVersion: v1
          kind: Node
          metadata:
            name: worker1.pink.edu.ihost.com
            labels:
              cluster.ocs.openshift.io/openshift-storage: ""
```

I've seen some other policies in this repo that are doing the same thing; but it doesn't seem to work. 
[community/CM-Configuration-Management/policy-label-worker-nodes.yaml](https://github.com/open-cluster-management-io/policy-collection/blob/main/community/CM-Configuration-Management/policy-label-worker-nodes.yaml)

I'm using openshift 4.13 an ACM 2.8.0
Any Idea ?
