### ISSUE TITLE
OpenShiftPlus-PolicySet should also have a policy to configure search

### ISSUE THREAD

**Issue by ch-stark** [open-cluster-management-io/policy-collection#462]
if you check:
https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.9/html-single/observability/index#searching-in-the-console-intro

goals
1. raise awareness of feature
2. give some good defaults
3. raise awareness of configuration-options and needs

```
apiVersion: search.open-cluster-management.io/v1alpha1
kind: Search
metadata:
  name: search-v2-operator
  namespace: open-cluster-management
spec:
  deployments:
    collector:
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 250m
          memory: 64Mi
    indexer:
      replicaCount: 3
    database:
        envVar:
          - name: POSTGRESQL_EFFECTIVE_CACHE_SIZE
            value: 1024MB
          - name: POSTGRESQL_SHARED_BUFFERS
            value: 512MB
          - name: WORK_MEM
            value: 128MB
    queryapi:
      arguments: 
      - -v=3
```
