### ISSUE TITLE
Gatekeeper policy to create/update config CR is deprecated.

### ISSUE THREAD

**Issue by harpasin** [open-cluster-management-io/policy-collection#519]
[Gatekeeper Exclude Namespace Policy](https://github.com/open-cluster-management-io/policy-collection/blob/main/community/CM-Configuration-Management/policy-gatekeeper-config-exclude-namespaces.yaml) is not working with the latest gatekeeper operator. 

The `config` CR edits are not allowed. You can not directly configure `Config` CR. The Gatekeeper Operator (0.5.0+) reconciled the `Config` CR.

To exclude namespace, You have to update the `Gatekeeper` CR:

```
apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  config:
    matches:
      - excludedNamespaces: ["user-defined-namespace"]
        processes: ["*"]
    disableDefaultMatches: false
```

The `disableDefaultMatches: false` field will keep default namespaces excluded.
